<?xml version="1.0" encoding="utf-8"?><Database Name="InetMagaz" Class="InetMagazDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.4.106\MSSQLSERVER2008;Initial Catalog=InetMagaz;User ID=test" SettingsObjectName="InetMagazLibrary.Properties.Settings" SettingsPropertyName="InetMagazConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.History" Member="Histories">
    <Type Name="History">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDlog" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HistoryProducts" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Emai" Type="System.String" DbType="VarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="isAdmin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.Search" Method="Search">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SearchResult">
      <Column Name="RESULT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUser" Method="GetUser">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetUserResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Emai" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertUser" Method="InsertUser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertGame" Method="InsertGame">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ImageUrl" Parameter="imageUrl" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Price" Parameter="price" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
</Database>